# Generated by Django 3.1.1 on 2021-09-17 22:25

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
